import { network } from "hardhat";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function main() {
  const { ethers } = await network.create();

  const [deployer] = await ethers.getSigners();
  console.log("Deploying with account:", deployer.address);
  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("Account balance:", ethers.formatEther(balance), "ETH\n");

  // Step 1: Deploy BackerBadge with deployer as initial owner
  console.log("1/3  Deploying BackerBadge NFT…");
  const badge = await ethers.deployContract("BackerBadge", [deployer.address], {
    gasLimit: 6_000_000n,
  });
  const badgeAddress = await badge.getAddress();
  console.log("     ✅ BackerBadge deployed to:", badgeAddress);

  // Step 2: Deploy CrowdfundingEscrow pointing at the badge
  console.log("2/3  Deploying CrowdfundingEscrow…");
  const contract = await ethers.deployContract("CrowdfundingEscrow", [badgeAddress], {
    gasLimit: 8_000_000n,
  });
  const contractAddress = await contract.getAddress();
  console.log("     ✅ CrowdfundingEscrow deployed to:", contractAddress);

  // Step 3: Transfer BackerBadge ownership to CrowdfundingEscrow
  console.log("3/3  Transferring BackerBadge ownership to CrowdfundingEscrow…");
  const tx = await badge.transferOwnership(contractAddress);
  await tx.wait();
  console.log("     ✅ Ownership transferred\n");

  console.log("─── Verify commands ─────────────────────────────────────────────");
  console.log(`npx hardhat --network sepolia verify ${contractAddress} ${badgeAddress}`);
  console.log(`npx hardhat --network sepolia verify ${badgeAddress} ${deployer.address}`);

  // Read ABI from compiled artifact
  const artifactPath = path.join(
    __dirname,
    "../artifacts/contracts/CrowdfundingEscrow.sol/CrowdfundingEscrow.json"
  );
  if (!fs.existsSync(artifactPath)) {
    console.error("Artifact not found — run: npx hardhat compile first.");
    return;
  }
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));

  // Write config to frontend
  const frontendConfigPath = path.join(__dirname, "../../frontend/lib/contractConfig.ts");
  const configContent = `// Auto-generated by deploy script – do not edit manually
export const CONTRACT_ADDRESS = "${contractAddress}" as const;
export const BACKER_BADGE_ADDRESS = "${badgeAddress}" as const;
export const NETWORK_NAME = "sepolia";
export const CHAIN_ID = 11155111;

export const ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;
  fs.writeFileSync(frontendConfigPath, configContent);
  console.log("✅ Frontend config → frontend/lib/contractConfig.ts");

  // Also update frontend/.env.local so Vercel picks it up
  const envLocalPath = path.join(__dirname, "../../frontend/.env.local");
  let envLocal = fs.existsSync(envLocalPath) ? fs.readFileSync(envLocalPath, "utf8") : "";
  const upsert = (key, val) => {
    const re = new RegExp(`^${key}=.*$`, "m");
    return re.test(envLocal) ? envLocal.replace(re, `${key}=${val}`) : `${envLocal}\n${key}=${val}`;
  };
  envLocal = upsert("NEXT_PUBLIC_CONTRACT_ADDRESS", contractAddress);
  envLocal = upsert("NEXT_PUBLIC_BACKER_BADGE_ADDRESS", badgeAddress);
  envLocal = upsert("NEXT_PUBLIC_CHAIN_ID", "11155111");
  fs.writeFileSync(envLocalPath, envLocal);
  console.log("✅ frontend/.env.local updated");
  console.log("\n═══════════════════════════════════════════════════════════════");
  console.log(" CrowdfundingEscrow:", contractAddress);
  console.log(" BackerBadge NFT:   ", badgeAddress);
  console.log(" Network:            Sepolia (11155111)");
  console.log("═══════════════════════════════════════════════════════════════");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
