/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace CrowdfundingEscrow {
      
    export type CampaignStruct = {id: BigNumberish, creator: AddressLike, title: string, description: string, goal: BigNumberish, raisedAmount: BigNumberish, deadline: BigNumberish, status: BigNumberish, contributorCount: BigNumberish}

    export type CampaignStructOutput = [id: bigint, creator: string, title: string, description: string, goal: bigint, raisedAmount: bigint, deadline: bigint, status: bigint, contributorCount: bigint] & {id: bigint, creator: string, title: string, description: string, goal: bigint, raisedAmount: bigint, deadline: bigint, status: bigint, contributorCount: bigint }
  

    export type MilestoneStruct = {title: string, amount: BigNumberish, completed: boolean, approved: boolean, votingOpen: boolean, approvalVotes: BigNumberish, rejectionVotes: BigNumberish, votingDeadline: BigNumberish}

    export type MilestoneStructOutput = [title: string, amount: bigint, completed: boolean, approved: boolean, votingOpen: boolean, approvalVotes: bigint, rejectionVotes: bigint, votingDeadline: bigint] & {title: string, amount: bigint, completed: boolean, approved: boolean, votingOpen: boolean, approvalVotes: bigint, rejectionVotes: bigint, votingDeadline: bigint }
  
    }

  export interface CrowdfundingEscrowInterface extends Interface {
    getFunction(nameOrSignature: "VOTING_PERIOD" | "addMilestone" | "backerBadge" | "campaignCount" | "campaignMilestones" | "campaigns" | "claimRefund" | "contribute" | "contributions" | "createCampaign" | "finalizeMilestoneVoting" | "getAllCampaigns" | "getCampaign" | "getContributors" | "getMilestoneVoteStatus" | "getMilestones" | "milestoneVoted" | "owner" | "pause" | "paused" | "refundClaimed" | "renounceOwnership" | "requestMilestonePayout" | "settleCampaign" | "transferOwnership" | "unpause" | "voteOnMilestone"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CampaignCreated" | "ContributionReceived" | "FundsReleased" | "MilestoneApproved" | "MilestoneRequested" | "OwnershipTransferred" | "Paused" | "RefundClaimed" | "Unpaused" | "VoteCast"): EventFragment;

    encodeFunctionData(functionFragment: 'VOTING_PERIOD', values?: undefined): string;
encodeFunctionData(functionFragment: 'addMilestone', values: [BigNumberish, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'backerBadge', values?: undefined): string;
encodeFunctionData(functionFragment: 'campaignCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'campaignMilestones', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'campaigns', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimRefund', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'contribute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'contributions', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'createCampaign', values: [string, string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'finalizeMilestoneVoting', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllCampaigns', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCampaign', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getContributors', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMilestoneVoteStatus', values: [BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getMilestones', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'milestoneVoted', values: [BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'refundClaimed', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'requestMilestonePayout', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'settleCampaign', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'voteOnMilestone', values: [BigNumberish, BigNumberish, boolean]): string;

    decodeFunctionResult(functionFragment: 'VOTING_PERIOD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'backerBadge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'campaignCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'campaignMilestones', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'campaigns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimRefund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contribute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contributions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeMilestoneVoting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllCampaigns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getContributors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMilestoneVoteStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMilestones', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'milestoneVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundClaimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestMilestonePayout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settleCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voteOnMilestone', data: BytesLike): Result;
  }

  
    export namespace CampaignCreatedEvent {
      export type InputTuple = [campaignId: BigNumberish, creator: AddressLike, title: string, goal: BigNumberish, deadline: BigNumberish];
      export type OutputTuple = [campaignId: bigint, creator: string, title: string, goal: bigint, deadline: bigint];
      export interface OutputObject {campaignId: bigint, creator: string, title: string, goal: bigint, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ContributionReceivedEvent {
      export type InputTuple = [campaignId: BigNumberish, contributor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [campaignId: bigint, contributor: string, amount: bigint];
      export interface OutputObject {campaignId: bigint, contributor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsReleasedEvent {
      export type InputTuple = [campaignId: BigNumberish, milestoneIndex: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [campaignId: bigint, milestoneIndex: bigint, amount: bigint];
      export interface OutputObject {campaignId: bigint, milestoneIndex: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneApprovedEvent {
      export type InputTuple = [campaignId: BigNumberish, milestoneIndex: BigNumberish];
      export type OutputTuple = [campaignId: bigint, milestoneIndex: bigint];
      export interface OutputObject {campaignId: bigint, milestoneIndex: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneRequestedEvent {
      export type InputTuple = [campaignId: BigNumberish, milestoneIndex: BigNumberish, title: string, amount: BigNumberish];
      export type OutputTuple = [campaignId: bigint, milestoneIndex: bigint, title: string, amount: bigint];
      export interface OutputObject {campaignId: bigint, milestoneIndex: bigint, title: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundClaimedEvent {
      export type InputTuple = [campaignId: BigNumberish, contributor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [campaignId: bigint, contributor: string, amount: bigint];
      export interface OutputObject {campaignId: bigint, contributor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoteCastEvent {
      export type InputTuple = [campaignId: BigNumberish, milestoneIndex: BigNumberish, voter: AddressLike, approved: boolean];
      export type OutputTuple = [campaignId: bigint, milestoneIndex: bigint, voter: string, approved: boolean];
      export interface OutputObject {campaignId: bigint, milestoneIndex: bigint, voter: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CrowdfundingEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): CrowdfundingEscrow;
    waitForDeployment(): Promise<this>;

    interface: CrowdfundingEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    VOTING_PERIOD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    addMilestone: TypedContractMethod<
      [_campaignId: BigNumberish, _title: string, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    backerBadge: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    campaignCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    campaignMilestones: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, bigint, boolean, boolean, boolean, bigint, bigint, bigint] & {title: string, amount: bigint, completed: boolean, approved: boolean, votingOpen: boolean, approvalVotes: bigint, rejectionVotes: bigint, votingDeadline: bigint }],
      'view'
    >
    

    
    campaigns: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, bigint, bigint] & {id: bigint, creator: string, title: string, description: string, goal: bigint, raisedAmount: bigint, deadline: bigint, status: bigint, contributorCount: bigint }],
      'view'
    >
    

    
    claimRefund: TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    contribute: TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    contributions: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    createCampaign: TypedContractMethod<
      [_title: string, _description: string, _goal: BigNumberish, _duration: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    finalizeMilestoneVoting: TypedContractMethod<
      [_campaignId: BigNumberish, _milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAllCampaigns: TypedContractMethod<
      [],
      [CrowdfundingEscrow.CampaignStructOutput[]],
      'view'
    >
    

    
    getCampaign: TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [CrowdfundingEscrow.CampaignStructOutput],
      'view'
    >
    

    
    getContributors: TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    getMilestoneVoteStatus: TypedContractMethod<
      [_campaignId: BigNumberish, _milestoneIndex: BigNumberish, _voter: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    getMilestones: TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [CrowdfundingEscrow.MilestoneStructOutput[]],
      'view'
    >
    

    
    milestoneVoted: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    refundClaimed: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    requestMilestonePayout: TypedContractMethod<
      [_campaignId: BigNumberish, _milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    settleCampaign: TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    voteOnMilestone: TypedContractMethod<
      [_campaignId: BigNumberish, _milestoneIndex: BigNumberish, _approve: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'VOTING_PERIOD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'addMilestone'): TypedContractMethod<
      [_campaignId: BigNumberish, _title: string, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'backerBadge'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'campaignCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'campaignMilestones'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, bigint, boolean, boolean, boolean, bigint, bigint, bigint] & {title: string, amount: bigint, completed: boolean, approved: boolean, votingOpen: boolean, approvalVotes: bigint, rejectionVotes: bigint, votingDeadline: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'campaigns'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, bigint, bigint] & {id: bigint, creator: string, title: string, description: string, goal: bigint, raisedAmount: bigint, deadline: bigint, status: bigint, contributorCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'claimRefund'): TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'contribute'): TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'contributions'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createCampaign'): TypedContractMethod<
      [_title: string, _description: string, _goal: BigNumberish, _duration: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalizeMilestoneVoting'): TypedContractMethod<
      [_campaignId: BigNumberish, _milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllCampaigns'): TypedContractMethod<
      [],
      [CrowdfundingEscrow.CampaignStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getCampaign'): TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [CrowdfundingEscrow.CampaignStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getContributors'): TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getMilestoneVoteStatus'): TypedContractMethod<
      [_campaignId: BigNumberish, _milestoneIndex: BigNumberish, _voter: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getMilestones'): TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [CrowdfundingEscrow.MilestoneStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'milestoneVoted'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'refundClaimed'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestMilestonePayout'): TypedContractMethod<
      [_campaignId: BigNumberish, _milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'settleCampaign'): TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'voteOnMilestone'): TypedContractMethod<
      [_campaignId: BigNumberish, _milestoneIndex: BigNumberish, _approve: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CampaignCreated'): TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
getEvent(key: 'ContributionReceived'): TypedContractEvent<ContributionReceivedEvent.InputTuple, ContributionReceivedEvent.OutputTuple, ContributionReceivedEvent.OutputObject>;
getEvent(key: 'FundsReleased'): TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
getEvent(key: 'MilestoneApproved'): TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
getEvent(key: 'MilestoneRequested'): TypedContractEvent<MilestoneRequestedEvent.InputTuple, MilestoneRequestedEvent.OutputTuple, MilestoneRequestedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RefundClaimed'): TypedContractEvent<RefundClaimedEvent.InputTuple, RefundClaimedEvent.OutputTuple, RefundClaimedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'VoteCast'): TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;

    filters: {
      
      'CampaignCreated(uint256,address,string,uint256,uint256)': TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
      CampaignCreated: TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
    

      'ContributionReceived(uint256,address,uint256)': TypedContractEvent<ContributionReceivedEvent.InputTuple, ContributionReceivedEvent.OutputTuple, ContributionReceivedEvent.OutputObject>;
      ContributionReceived: TypedContractEvent<ContributionReceivedEvent.InputTuple, ContributionReceivedEvent.OutputTuple, ContributionReceivedEvent.OutputObject>;
    

      'FundsReleased(uint256,uint256,uint256)': TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
      FundsReleased: TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
    

      'MilestoneApproved(uint256,uint256)': TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
      MilestoneApproved: TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
    

      'MilestoneRequested(uint256,uint256,string,uint256)': TypedContractEvent<MilestoneRequestedEvent.InputTuple, MilestoneRequestedEvent.OutputTuple, MilestoneRequestedEvent.OutputObject>;
      MilestoneRequested: TypedContractEvent<MilestoneRequestedEvent.InputTuple, MilestoneRequestedEvent.OutputTuple, MilestoneRequestedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RefundClaimed(uint256,address,uint256)': TypedContractEvent<RefundClaimedEvent.InputTuple, RefundClaimedEvent.OutputTuple, RefundClaimedEvent.OutputObject>;
      RefundClaimed: TypedContractEvent<RefundClaimedEvent.InputTuple, RefundClaimedEvent.OutputTuple, RefundClaimedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'VoteCast(uint256,uint256,address,bool)': TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
      VoteCast: TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
    
    };
  }